# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: leaveitto.me
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  secret_key_base: 1643a3b3b0c24576720a41feb337e612cfef7641eb3d5dd1ca9ed8cc41a3776cafabe3a3c4e6c8e6908d5260e0a2476e1d1ee2b57e5cdd0bd8f64764bac1c29f

test:
  secret_key_base: 1643a3b3b0c24576720a41feb337e612cfef7641eb3d5dd1ca9ed8cc41a3776cafabe3a3c4e6c8e6908d5260e0a2476e1d1ee2b57e5cdd0bd8f64764bac1c29f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
